# MySQL Configuration
    - name: Instalando pacotes MySQL
      yum: 
        name:
          - mysql-server
          - php-mysqlnd
          - python3-PyMySQL
        state: latest
 
    - name: Startando o serviço
      systemd: 
        name: mysqld
        state: started 
        enabled: yes
 
    - name: Setar senha Root MySQL
      mysql_user:
        login_host: 'localhost'
        login_user: 'root'
        login_password: 'senha'
        name: 'root'
        password: '{{ mysql_root_password }}'
        state: present
 
    - name: Criando DB para o MySQL
      mysql_db:
        name: "{{ mysql_db }}"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"
 
    - name: Criando usuário MySQL para o WordPress
      mysql_user:
        name: "{{ mysql_user }}"
        password: "{{ mysql_password }}"
        priv: "{{ mysql_db }}.*:ALL"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"
