#MySQL Settings
mysql_root_password: "setar-senha-root-mysql"
mysql_db: "nome-do-banco"
mysql_user: "usuario"
mysql_password: "senha-usuario"
 
#HTTP Settings
http_host: "wp.example.com" #validar server
http_conf: "wp.example.com.conf" #validar server
http_port: "80" #Validar porta 443 (https)
