- name: Instalar repositório Remi PHP
  dnf:
    name: 'http://rpms.remirepo.net/enterprise/remi-release-8.rpm'
    update_cache: yes
    state: present

- name: Habilitar o repositório Remi PHP
  command: dnf module reset php -y
  command: dnf module enable php:remi-7.4 -y

- name: Instalar extensões PHP
  yum: name={{ item }} update_cache=yes state=latest
  loop: "{{ php_modules }}"
