- name: Instalando o repositório REMI
  dnf: 
    name: 'http://rpms.remirepo.net/enterprise/remi-release-8.rpm' 
    state: present
 
- name: EHabilitando repositório
  command: dnf module reset php -y
  command: dnf module enable php:remi-7.4 -y
 
- name: Instalar módulos PHP
  dnf: 
    name:
      - php
      - php-cli
      - php-common
      - php-curl
      - php-gd
      - php-mbstring
      - php-xml
      - php-xmlrpc
      - php-soap
      - php-intl 
      - php-zip 
      - php-fpm
    state: latest
  
